#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && (flake8 --format=html --htmldir=flake-report --exclude=src/grammar src|| true) && cd flake-report/ && python3 -m http.server
